# Generated by Django 4.0.1 on 2022-01-17 19:42

import books.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='The book title', max_length=100, verbose_name='Title')),
                ('added_dt', models.DateTimeField(auto_now_add=True, verbose_name='Added at')),
                ('isbn', models.CharField(blank=True, help_text='International Standard Book Number', max_length=13, null=True, validators=[django.core.validators.RegexValidator(message='10 or 13 digits', regex='\\d{13}')], verbose_name='IBSN')),
                ('author', models.CharField(max_length=50, verbose_name='Author')),
                ('publisher', models.CharField(blank=True, max_length=100, null=True, verbose_name='Publisher')),
                ('publish_dt', models.DateField(verbose_name='Published at')),
                ('description', models.TextField(blank=True, max_length=1000, null=True, verbose_name='Description')),
                ('cover_img', models.ImageField(upload_to='cover_img/', verbose_name='Cover image')),
                ('file', models.FileField(upload_to=books.models.user_directory_path, validators=[django.core.validators.FileExtensionValidator(['pdf'], message="the file must be '.pdf'.")], verbose_name='Book file')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, null=True, verbose_name='Slug')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Uploaded by')),
            ],
            options={
                'verbose_name': 'Book',
                'verbose_name_plural': 'Books',
            },
        ),
    ]
